// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HighlightRecord = { text_id: string, group_id: string, start: number, end: number, color: string, };