// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HighlightRecord } from "./HighlightRecord";
import type { InputRecord } from "./InputRecord";
import type { OutputRecord } from "./OutputRecord";

export type Task = { input: InputRecord, output: OutputRecord | null, highlights: Array<HighlightRecord>, origin: string, postponed: string | null, };